---
- name: Install Docker and prepare environment
  hosts: homeserver
  become: true
  gather_facts: false

  tasks:
    - name: Install Docker package
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: true
