---
- name: Harden SSH configuration but allow LAN access
  hosts: homeserver
  become: true
  gather_facts: true

  tasks:
    - name: Get LAN IPv4 address
      ansible.builtin.set_fact:
        ssh_listen_ip: "{{ ansible_default_ipv4.address }}"

    - name: Ensure SSH listens only on LAN IP
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?ListenAddress'
        line: "ListenAddress {{ ssh_listen_ip }}"
        create: true
        owner: root
        group: root
        mode: '0600'

    - name: Disable SSH password authentication by default
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'

    - name: Allow password authentication only for LAN
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        marker: "# {mark} LAN Password Authentication"
        block: |
          Match Address 192.168.0.0/16
              PasswordAuthentication yes

    - name: Restart SSH service to apply changes
      ansible.builtin.service:
        name: ssh
        state: restarted
